#define MESSAGE_PROCESSOR_TASK_ID 0
#define SERVICE_IPC_TASK_ID 1

#define TASK_EVENT_QUEUE_LEN 16
#define SERVICE_IPC_QUEUE_LEN 32

//#define MIST_FOLLOW_TASK_ID 2
//#define FOLLOW_EVENT_QUEUE_LEN 1

